name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: '17.0'
      - name: Create build directory
        run: |
          mkdir build
      - name: Build
        run: |
          cd build
          cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build . --config Debug
      - name: Run engine
        run: |
          cd build/Debug
          UltraEngine.exe
